name: Build, Push and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1  # Change to your desired AWS region
  ECR_REPOSITORY: deployapplication  # Replace with your ECR repository name
  # AWS_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  ECR_REGISTRY: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Terraform_Init'
        id: tfinit
        if: github.ref == 'refs/heads/master'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.4.6
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./Terraform"

      - name: 'Terraform_Plan'
        id: tfplan
        if: github.ref == 'refs/heads/master'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.4.6
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "./Terraform"

      - name: 'Terraform_Apply'
        id: tfapply
        if: github.ref == 'refs/heads/master'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.4.6
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./Terraform"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          IMAGE_TAG=$GITHUB_SHA
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f BookManager/Dockerfile BookManager/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: 'Deployment to EC2 Instance'
        run: |
          # Set environment variables
          printf "sonarqube_public_ip=%s\n" $(terraform -chdir="./Terraform" output -raw sonarqube_public_ip) >> $GITHUB_ENV
          printf "nexus_public_ip=%s\n" $(terraform -chdir="./Terraform" output -raw nexus_public_ip) >> $GITHUB_ENV

          # Output the private key to a file and set the correct permissions
          terraform -chdir="./Terraform" output -raw private_key > key.pem
          chmod 600 key.pem

          EC2_IP=$(terraform -chdir="./Terraform" output -raw deployment_instance_public_ip) 
          AWS_REGION=${{ env.AWS_REGION }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE=${{ env.image }}

          # SSH into the EC2 instance and execute commands
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_IP << EOF
            # Update and install required packages
            sudo apt-get update -y
            sudo apt-get install -y docker.io awscli

            # Start and enable Docker
            sudo systemctl start docker
            sudo systemctl enable docker

            # Add the current user to Docker group
            sudo usermod -aG docker \$USER

            # Log into Docker registry non-interactively
            aws_ecr_login=\$(aws ecr get-login-password --region $AWS_REGION)
            echo \$aws_ecr_login | sudo docker login --username AWS --password-stdin $ECR_REGISTRY

            # Pull the Docker image
            sudo docker pull $IMAGE

            # Run Docker container
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            sudo docker run -d --name myapp -p 80:80 $IMAGE
          EOF
        shell: /usr/bin/bash -e {0}       

      # - name: Terraform Destroy
      #   if: failure()
      #   run: terraform destroy -auto-approve ./Terraform

      - name: 'Terraform_Destroy'
        id: tfdestroy
        if: github.ref == 'refs/heads/master' && always()
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.4.6
          tf_actions_subcommand: 'destroy'
          tf_actions_working_dir: "./Terraform"