name: Build, Push and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your desired AWS region


      # - name: Build, tag, and push Django image to Amazon ECR
      #   id: django-build-image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     # Build a docker container and
      #     # push it to ECR so that it can
      #     # be deployed to ECS.
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f snowball/django.Dockerfile snowball/
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      #     echo "django_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push
  #   steps:
  #     - name: Deploy to EC2
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.EC2_HOST }}
  #         username: Deployment  # Replace with your EC2 instance's username, e.g., ubuntu
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           # Ensure Docker is installed
  #           sudo apt-get update -y
  #           sudo apt-get install -y docker.io
  #           sudo systemctl start docker
  #           sudo systemctl enable docker
  #           sudo usermod -aG docker $USER

  #           # Logout and login to apply usermod changes - not needed in script
  #           # Pull and run the Docker image
  #           docker pull ${{ env.IMAGE_URI }}
  #           docker stop myapp || true
  #           docker rm myapp || true
  #           docker run -d --name myapp -p 80:80 ${{ env.IMAGE_URI }}
