name: Destroy Infrastructure

on:
  workflow_dispatch: # Triggered manually

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  destroy_infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform
        id: tf_init
        if: github.ref == 'refs/heads/master'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.4.6
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./Terraform"

      - name: Destroy Infrastructure
        id: tf_destroy
        if: always() # Always execute, even if previous steps fail
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.4.6
          tf_actions_subcommand: 'destroy'
          tf_actions_working_dir: "./Terraform"
